/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      borderRadius: {
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        full: '9999px',
      },
      fontFamily: {
        sans: ['"Public Sans"', 'system-ui', 'sans-serif'],
      },
      colors: {
        primary: '#b99fff',
        'on-primary': '#38008d',
        'primary-container': '#ad8eff',
        'on-primary-container': '#2b006f',
        'primary-dim': '#844eff',
        'on-primary-fixed-variant': '#350087',
        secondary: '#00e3fd',
        'on-secondary': '#004d57',
        'secondary-container': '#006875',
        'on-secondary-container': '#e8fbff',
        'secondary-dim': '#00d4ec',
        tertiary: '#ff51fa',
        'on-tertiary': '#400040',
        error: '#ff6e84',
        'on-error': '#490013',
        'error-container': '#a70138',
        surface: '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-bright': '#2c2c2c',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#191a1a',
        'surface-container-high': '#1f2020',
        'surface-container-highest': '#262626',
        'on-surface': '#ffffff',
        'on-surface-variant': '#adaaaa',
        background: '#0e0e0e',
        'on-background': '#ffffff',
        outline: '#767575',
        'outline-variant': '#484848',
      },
    },
  },
  plugins: [],
};
